config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "home/index"
  get "home/credits"
  get "dashboard/index"
  get "dashboard/search"
  get "dashboard/whatsup"
  get "dashboard/peruser"

  resources :roads
  resources :transports
  resources :places
  resources :structures
  resources :reasons
  resources :veichles
  resources :refunds do
    collection do
      get :print
      get :print_list
    end
  end
  resources :refund_closures do
    collection do
      get :search
    end
  end
  resources :holidays do
    collection do
      get :search
    end
  end
  resources :hourly_holidays do
    collection do
      get :search
    end
  end
  resources :diseases do
    collection do
      get :search
    end
  end
  resources :permits do
    collection do
      get :search
    end
  end
  resources :hourly_permits do
    collection do
      get :search
    end
  end

  devise_for :users, skip: [:registrations]
  as :user do
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"
    resources :users, only: [:index, :show]
  end

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
end

app/models/holiday.rb
class Holiday < ApplicationRecord
  belongs_to :user

  validates :user_id, :start_time, :end_time, presence: true

  validate :congruent_date_range

  def congruent_date_range
    if !end_time.blank? and end_time < start_time
      errors.add(:end_time, "Data Fine non puo essere minore di Data Inizio")
    end
  end
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  load_and_authorize_resource

  before_action :set_holiday, only: %i[ show edit update destroy ]

  def index
    if current_user.god == true
      @q = Holiday.ransack(params[:q])
      @holidays = @q.result(distinct: true)
    elsif current_user.manager == true
      @q = Holiday.ransack(params[:q])
      @holidays = @q.result(distinct: true).where(user_id: User.where(province: current_user.province, region: current_user.region))
    else
      @q = Holiday.ransack(params[:q])
      @holidays = @q.result(distinct: true).where(user_id: current_user)
    end
  end

  def show
    @holiday = Holiday.find(params[:id])
  end

  def new
    @holiday = Holiday.new
  end

  def edit
  end

  def create
    unless current_user.god == true || current_user.manager == true
      @holiday = current_user.holidays.build(holiday_params)
    else
      @holiday = Holiday.new(holiday_params)
    end

    @holiday.creator = "#{current_user.last_name} #{current_user.first_name}"

    if @holiday.save
      HolidayMailer.with(user: current_user, holiday: @holiday).holiday_email.deliver_later
      redirect_to holidays_path, notice: "holiday was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @holiday.updater = "#{current_user.last_name} #{current_user.first_name}"
    @holiday.update_date = Date.today

    if @holiday.update(holiday_params)
      HolidayMailer.with(user: current_user, holiday: @holiday).holiday_email_update.deliver_later
      redirect_to holidays_path, notice: "holiday was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @holiday.destroy
    HolidayMailer.with(user: current_user).holiday_email_destroy.deliver_later
    redirect_to holidays_url, notice: "holiday was successfully destroyed."
  end

  def search
    if current_user.god == true
      @q = Holiday.ransack(params[:q])
      @holidays = @q.result(distinct: true).includes(:user).order("users.last_name ASC")
      @holidays = @holidays.order("start_time DESC").page(params[:page])
    elsif current_user.manager == true
      @q = Holiday.ransack(params[:q])
      @holidays = @q.result(distinct: true).where(user_id: User.where(province: current_user.province, region: current_user.region)).includes(:user).order("users.last_name ASC")
      @holidays = @holidays.order("start_time DESC").page(params[:page])
    else
      @q = Holiday.ransack(params[:q])
      @holidays = @q.result(distinct: true).where(user_id: current_user).order("start_time DESC").page(params[:page])
    end
  end

  private

  def set_holiday
    @holiday = Holiday.find(params[:id])
  end

  def holiday_params
    params.require(:holiday).permit(:user_id, :start_time, :end_time, :note, :updater, :update_date, :processed)
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
  def holiday_full_user(holiday)
    "#{holiday.user.first_name} #{holiday.user.last_name}"
  end

  def holiday_duration(holiday)
    @sweeknumber = holiday.start_time.cweek.to_i()
    @eweeknumber = holiday.end_time.cweek.to_i()
    @period = @eweeknumber - @sweeknumber

    if @period < 1
      @timeamount = TimeDifference.between(holiday.start_time, holiday.end_time).in_days
      @timeamount = @timeamount + 1
    else
      @timeamount = TimeDifference.between(holiday.start_time, holiday.end_time).in_days
      @timeamount = @timeamount - ((@period * 2) - 1)
    end
  end

  def holiday_range(holiday)
    Date.today >= holiday.start_time && Date.today <= holiday.end_time
  end

  def startholiday(holiday)
    holiday.start_time
  end

  def endholiday(holiday)
    holiday.end_time
  end

  def processed_holiday(holiday)
    holiday.processed == true
  end

  def same_month(holiday)
    if holiday.start_time.month == holiday.end_time.month
      "#{l(holiday.start_time, format: "%B")}"
    else
      "#{l(holiday.start_time, format: "%B")} - #{l(holiday.end_time, format: "%B")}"
    end
  end
end

app/views/holidays/_detail.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header mb-5">
          <div class="modal-title">
            <%= image_tag("holidays_form_icon.svg", class: "img-fluid") %>
          </div>
          <a class="modal-header-link" data-bs-dismiss="modal" aria-label="Close">
            <i class="fa-solid fa-xmark"></i>
          </a>
        </div>
        <div class="modal-body mb-5">
          <div class="col-8 offset-2">
            <div id="<%= dom_id @holiday %>" class="scaffold_record">
              <div class="row">
                <div class="col">
                  <h3 class="text-primary">
                    <%= holiday_full_user(@holiday) %>
                  </h3>
                  <hr class="bg-primary"/>
                  <h5 class="text-primary">
                    Dal giorno:
                    &emsp;
                    <strong>
                      <%= l(@holiday.start_time, format: "%A %d %B %Y") %>
                    </strong>
                    &emsp;
                    al giorno:
                    &emsp;
                    <strong>
                      <%= l(@holiday.end_time, format: "%A %d %B %Y") %>
                    </strong>
                    <hr/>
                    Note:
                    <br/>
                    <br/>
                    <span class="text-dark">
                      <%= @holiday.note %>
                    </span>
                  </h5>
                  <hr class="bg-primary"/>
                  <br/>
                  <span class="float-start">
                    <small class="text-secondary">
                      Creato da:
                      &nbsp;
                      <%= @holiday.creator %>
                      &emsp;
                      Data Creazione:
                      &nbsp;
                      <%= l(@holiday.created_at, format: "%A %d %B %Y") %>
                    </small>
                  </span>
                  <br/>
                  <% if @holiday.update_date.present? %>
                    <span class="float-start">
                      <small class="text-secondary">
                        Aggiornato da:
                        &nbsp;
                        <%= @holiday.updater %>
                        &emsp;
                        Data Ultimo Aggiornamento:
                        &nbsp;
                        <%= l(@holiday.update_date, format: "%A %d %B %Y") %>
                      </small>
                    </span>
                  <% end %>
                  <br/>
                  <span class="float-end">
                    <small class="text-success">
                      <% if processed_holiday(holiday) %>
                        <i class="fa-solid fa-circle-check"></i>
                        &nbsp;
                        Presa Visione
                      <% end %>
                    </small>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/holidays/_form.html.erb
<%= form_with(model: holiday) do |form| %>
  <% if holiday.errors.any? %>
    <div style="color: red">
      <h4>
        Errore!&emsp;Non posso salvare per i seguenti motivi:
      </h4>
      <ul>
        <% holiday.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% unless current_user.regular == true %>
    <div class="input-group mb-1">
      <span class="input-group-text">
        <i class="fa-solid fa-user"></i>
        &nbsp;&nbsp;
        <%= form.label :user %>
      </span>
      <% unless current_user.god == true %>
        <%= form.collection_select :user_id, User.order('last_name ASC').where(province: current_user.province, region: current_user.region), :id, :user_name_full, {:include_blank => false}, {:class => 'form-control'} %>
      <% else %>
        <%= form.collection_select :user_id, User.order('last_name ASC'), :id, :user_name_full, {:include_blank => false}, {:class => 'form-control'} %>
      <% end %>
    </div>
  <% end %>
  <div class="input-group mb-1">
    <span class="input-group-text">
      <i class="fa-solid fa-calendar-day"></i>
      &nbsp;&nbsp;
      <%= form.label :start_date %>
    </span>
    <%= form.date_field :start_time, class: 'form-control' %>
  </div>
  <div class="input-group mb-1">
    <span class="input-group-text">
      <i class="fa-solid fa-calendar-day"></i>
      &nbsp;&nbsp;
      <%= form.label :end_date %>
    </span>
    <%= form.date_field :end_time, class: 'form-control' %>
  </div>
  <div class="input-group mb-2">
    <span class="input-group-text">
      <i class="fa-solid fa-pencil"></i>
      &nbsp;&nbsp;
      <%= form.label :note %>
    </span>
    <%= form.text_area :note, class: 'form-control' %>
  </div>
  <% unless current_user.regular == true %>
    <br/>
    <div class="form-check form-check-inline">
      <label class="form-check-label text-primary" for="checkboxPrefilled">
        Presa visione
        &nbsp;&nbsp;
        <i class="fa-solid fa-eye"></i>
      </label>
      <%= form.check_box :processed, class: 'form-check-input' %>
    </div>
    <br/>
    <br/>
  <% end %>
  <div class="d-grid">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/holidays/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header mb-5">
          <div class="modal-title">
            <%= image_tag("holidays_form_icon.svg", class: "img-fluid") %>
          </div>
          <a class="modal-header-link" data-bs-dismiss="modal" aria-label="Close">
            <i class="fa-solid fa-xmark"></i>
          </a>
        </div>
        <div class="modal-body mb-5">
          <div class="col-8 offset-2">
            <%= render "holidays/form", holiday: holiday %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/holidays/_holiday.html.erb
<div id="<%= dom_id holiday %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <%= holiday.id %>
  </p>
  <strong>Position:</strong>
  <%= holiday.start_time %>
</p>
</div>

app/views/holidays/edit.html.erb
<h1>Editing holiday</h1>
<%= render "form", holiday: @holiday %>
<br>
<div>
  <%= link_to "Show this holiday", @holiday %> |
  <%= link_to "Back to holidays", holidays_path %>
</div>

app/views/holidays/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "holidays/form_modal", locals: { holiday: @holiday } %>
<% end %>

app/views/holidays/index.html.erb
<div class="row">
  <div class="col-8">
    <h3 class='text-primary'>
      <%= image_tag("holidays_logo.svg", class: "img-fluid") %>
    </h3>
  </div>
  <div class="col-4">
    <div class="d-grid">
      <%= link_to new_holiday_path, "data-controller": "turbo", class: "btn btn-primary btn-sm shadow" do %>
        <i class="fa-solid fa-plus"></i>
        &nbsp;
        <i class="fa-solid fa-umbrella-beach"></i>
        &nbsp;
        Aggiungi Ferie
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <%= month_calendar(events: @holidays) do |date, holidays| %>
      <% if date.wday == 0 || date.wday == 6 %>
      <% else %>
        <div class='card card-calendar bg-light mb-1 shadow'>
          <div class='card-header card-header-calendar text-center'>
            <i class='fas fa-calendar-day'></i>
            &nbsp;
            <%= l(date, format: "%a %d") %>
            &emsp;
            <span class='text-secondary'>
              <%= l(date, format: "%b") %>
            </span>
          </div>
          <div class='card-body card-body-calendar'>
            <% holidays.each do |holiday| %>
              <% if holiday.user.color?%>
                <span class="badge" style="background-color: <%= "#{holiday.user.color}" %>">
                <% else %>
                  <span class="badge">
                  <% end %>
                  <%= link_to holiday_path(holiday), "data-controller": "turbo", "data-bs-toggle": "tooltip", "title": "Visualizza Dettaglio" do %>
                    <i class="fa-solid fa-circle-user"></i>
                    &nbsp;
                    <%= "#{holiday.user.last_name} #{holiday.user.first_name.split.map { |i| i[0, 1].upcase }.join}" %>
                  <% end %>
                  <% if holiday.processed == true %>
                  <% else %>
                    &emsp;
                    &emsp;
                    <%= link_to edit_holiday_path(holiday), "data-controller": "turbo", "data-bs-toggle": "tooltip", "title": "Modifica il Record Corrente" do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                    &nbsp;
                    &nbsp;
                    <%= link_to holiday_path(holiday), "data-turbo-method": :delete, "data-turbo-confirm": "Sicuri di voler eliminare il record corrente?", "data-bs-toggle": "tooltip", "title": "Elimina il Record Corrente" do %>
                      <i class="fa-solid fa-trash"></i>
                    <% end %>
                  <% end %>
                </span>
                <br/>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/holidays/new.html.erb
<h1>New Holiday</h1>
<%= render "form", holiday: @holiday %>
<br>
<div>
  <%= link_to "Back to holidays", holidays_path %>
</div>

app/views/holidays/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "holidays/form_modal", locals: { holiday: @holiday } %>
<% end %>

app/views/holidays/search.html.erb
<div class="row mb-4">
  <div class="col-12">
    <%= image_tag("holidays_logo.svg", class: "img-fluid") %>
  </div>
</div>
<%= search_form_for @q, id: "search-form", url: search_holidays_path do |form| %>
  <div class="row">
    <div class="col-4">
      <div class="input-group mb-2">
        <div class="input-group-search">
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;<span>Data Inizio</span>
        </div>
        <%= form.date_field :start_time_gteq, class: "form-control" %>
      </div>
    </div>
    <div class="col-4">
      <div class="input-group mb-2">
        <div class="input-group-search">
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;<span>Data Fine</span>
        </div>
        <%= form.date_field :start_time_lteq, class: "form-control" %>
      </div>
    </div>
    <div class="col-4">
      <span class="float-start">
        <div class="input-group mb-2">
          <div class="input-group-search">
            <i class="fa-solid fa-user-circle"></i>
            &nbsp;<span>Utente</span>
          </div>
          <% if god? %>
            <%= form.collection_select(:user_id_eq, User.order("last_name ASC"), :id, :user_name_full, { :include_blank => true }, { :class => "form-control" }) %>
          <% elsif manager? %>
            <%= form.collection_select :user_id_eq, User.order("last_name ASC").where(province: current_user.province, region: current_user.region), :id, :user_name_full, { :include_blank => true }, { :class => "form-control" } %>
          <% else %>
          <% end %>
        </div>
      </span>
      <span class="float-end pe-2">
        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          <i class="fa-solid fa-magnifying-glass"></i>
          &emsp;
          <strong>
            Cerca
          </strong>
        <% end %>
        &nbsp;
      </span>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-12">
    <br/>
    <table class="table table-hover text-primary">
      <thead>
        <th>
          <i class="fa-solid fa-user-circle"></i>
          &nbsp;
          Utente
        </th>
        <th>
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;
          Data Inizio
        </th>
        <th>
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;
          Data Fine
        </th>
        <th>
          <i class="fa-solid fa-calendar-days"></i>
          &nbsp;
          Durata
        </th>
      </thead>
      <tbody>
        <% @total = 0 %>
        <% @holidays.each do |holiday| %>
          <% if holiday.user.color? %>
            <tr style="background-color: <%= "#{holiday.user.color}" %>">
            <% else %>
              <tr>
              <% end %>
              <td>
                <%= link_to holiday_path(holiday), "data-controller": "turbo", "data-bs-toggle": "tooltip", "title": "Visualizza Dettaglio" do %>
                  <%= "#{holiday.user.first_name} #{holiday.user.last_name}" %>
                <% end %>
              </td>
              <td>
                <%= l(holiday.start_time, format: "%A %d %B %Y") %>
              </td>
              <td>
                <%= l(holiday.end_time, format: "%A %d %B %Y") %>
              </td>
              <td>
                <strong class='text-primary'>
                  <%= holiday_duration(holiday).round %>
                  &emsp;
                  <% unless holiday_duration(holiday) > 1 %>
                    giorno
                  <% else %>
                    giorni
                  <% end %>
                </strong>
              </td>
            </tr>
            <% @total = @total + holiday_duration(holiday).round %>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= paginate @holidays %>
    </div>
  </div>

app/views/holidays/show.html.erb
<%= render @holiday %>
<div>
  <%= link_to "Edit", edit_holiday_path(@holiday) %> |
  <%= link_to "Destroy", holiday_path(@holiday),
    "data-turbo-method": :delete,
    "data-turbo-confirm": "Are you sure?" %> |
  <%= link_to "Back to holidays", holidays_path %>
</div>

app/views/holidays/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "holidays/detail", locals: { holiday: @holiday } %>
<% end %>