config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "home/index"
  get "home/credits"
  get "dashboard/index"
  get "dashboard/search"
  get "dashboard/whatsup"
  get "dashboard/peruser"

  resources :roads
  resources :transports
  resources :places
  resources :structures
  resources :reasons
  resources :veichles
  resources :refunds do
    collection do
      get :print
      get :print_list
    end
  end
  resources :refund_closures do
    collection do
      get :search
    end
  end
  resources :holidays do
    collection do
      get :search
    end
  end
  resources :hourly_holidays do
    collection do
      get :search
    end
  end
  resources :diseases do
    collection do
      get :search
    end
  end
  resources :permits do
    collection do
      get :search
    end
  end
  resources :hourly_permits do
    collection do
      get :search
    end
  end

  devise_for :users, skip: [:registrations]
  as :user do
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"
    resources :users, only: [:index, :show]
  end

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
end

app/models/hourly_permit.rb
class HourlyPermit < ApplicationRecord
  belongs_to :user
  belongs_to :permit_type

  validates :user_id, :start_time, :end_time, :permit_type_id, presence: true

  validate :congruent_date_range

  def congruent_date_range
    if !end_time.blank? and end_time < start_time
      errors.add(:end_time, "Data Fine non puo essere minore di Data Inizio")
    end
    if !end_time.blank? and end_time.end_of_day != start_time.end_of_day
      errors.add(:end_time, "Le ore di ferie non possono eccedere oltre la giornata stessa")
    end
  end
end

app/controllers/hourly_permits_controller.rb
class HourlyPermitsController < ApplicationController
  load_and_authorize_resource

  before_action :set_hourly_permit, only: %i[ show edit update destroy ]

  def index
    if current_user.god == true
      @q = HourlyPermit.ransack(params[:q])
      @hourly_permits = @q.result(distinct: true)
    elsif current_user.manager == true
      @q = HourlyPermit.ransack(params[:q])
      @hourly_permits = @q.result(distinct: true).where(user_id: User.where(province: current_user.province, region: current_user.region))
    else
      @q = HourlyPermit.ransack(params[:q])
      @hourly_permits = @q.result(distinct: true).where(user_id: current_user)
    end
  end

  def show
    @hourly_permit = HourlyPermit.find(params[:id])
  end

  def new
    @hourly_permit = HourlyPermit.new
  end

  def edit
  end

  def create
    unless current_user.god == true || current_user.manager == true
      @hourly_permit = current_user.hourly_permits.build(hourly_permit_params)
    else
      @hourly_permit = HourlyPermit.new(hourly_permit_params)
    end

    @hourly_permit.creator = "#{current_user.last_name} #{current_user.first_name}"

    if @hourly_permit.save
      HourlyPermitMailer.with(user: current_user, hourly_permit: @hourly_permit).hourly_permit_email.deliver_later
      redirect_to hourly_permits_path, notice: "hourly_permit was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @hourly_permit.updater = "#{current_user.last_name} #{current_user.first_name}"
    @hourly_permit.update_date = Date.today

    if @hourly_permit.update(hourly_permit_params)
      HourlyPermitMailer.with(user: current_user, hourly_permit: @hourly_permit).hourly_permit_email_update.deliver_later
      redirect_to hourly_permits_path, notice: "hourly_permit was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @hourly_permit.destroy
    HourlyPermitMailer.with(user: current_user).hourly_permit_email_destroy.deliver_later
    redirect_to hourly_permits_url, notice: "hourly_permit was successfully destroyed."
  end

  def search
    if current_user.god == true
      @q = HourlyPermit.ransack(params[:q])
      @hourly_permits = @q.result(distinct: true).includes(:user).order("users.last_name ASC")
      @hourly_permits = @hourly_permits.order("start_time DESC").page(params[:page])
    elsif current_user.manager == true
      @q = HourlyPermit.ransack(params[:q])
      @hourly_permits = @q.result(distinct: true).where(user_id: User.where(province: current_user.province, region: current_user.region)).includes(:user).order("users.last_name ASC")
      @hourly_permits = @hourly_permits.order("start_time DESC").page(params[:page])
    else
      @q = HourlyPermit.ransack(params[:q])
      @hourly_permits = @q.result(distinct: true).where(user_id: current_user).order("start_time DESC").page(params[:page])
    end
  end

  private

  def set_hourly_permit
    @hourly_permit = HourlyPermit.find(params[:id])
  end

  def hourly_permit_params
    params.require(:hourly_permit).permit(:user_id, :start_time, :end_time, :note, :updater, :update_date, :processed, :permit_type_id)
  end
end

app/helpers/hourly_permits_helper.rb
module HourlyPermitsHelper
  def hourly_permit_full_user(hourly_permit)
    "#{hourly_permit.user.first_name} #{hourly_permit.user.last_name}"
  end

  def hourly_permit_duration(hourly_permit)
    @timeamount = TimeDifference.between(hourly_permit.start_time, hourly_permit.end_time).in_hours
  end

  def processed_hourly_permit(hourly_permit)
    hourly_permit.processed == true
  end
end

app/views/hourly_permits/_detail.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header mb-5">
          <div class="modal-title">
            <%= image_tag("hourly_permits_form_icon.svg", class: "img-fluid") %>
          </div>
          <a class="modal-header-link" data-bs-dismiss="modal" aria-label="Close">
            <i class="fa-solid fa-xmark"></i>
          </a>
        </div>
        <div class="modal-body mb-5">
          <div class="col-8 offset-2">
            <div id="<%= dom_id @hourly_permit %>" class="scaffold_record">
              <div class="row">
                <div class="col">
                  <h3 class="text-primary">
                    <%= hourly_permit_full_user(@hourly_permit) %>
                  </h3>
                  <hr class="bg-primary"/>
                  <h5 class="text-primary">
                    Il giorno:
                    &emsp;
                    <strong>
                      <%= l(@hourly_permit.start_time, format: "%A %d %B %Y") %>
                    </strong>
                    &emsp;
                    dalle ore:
                    <strong>
                      <%= l(@hourly_permit.start_time, format: "%H:%M") %>
                    </strong>
                    &emsp;
                    alle ore:
                    &emsp;
                    <strong>
                      <%= l(@hourly_permit.end_time, format: "%H:%M") %>
                    </strong>
                    <hr/>
                    Tipo Permesso:
                    &emsp;
                    <%= @hourly_permit.permit_type.name %>
                    <hr/>
                    Note:
                    <br/>
                    <br/>
                    <span class="text-dark">
                      <%= @hourly_permit.note %>
                    </span>
                  </h5>
                  <hr class="bg-primary"/>
                  <br/>
                  <br/>
                  <span class="float-start">
                    <small class="text-secondary">
                      Creato da:
                      &nbsp;
                      <%= @hourly_permit.creator %>
                      &emsp;
                      Data Creazione:
                      &nbsp;
                      <%= l(@hourly_permit.created_at, format: "%A %d %B %Y") %>
                    </small>
                  </span>
                  <br/>
                  <% if @hourly_permit.update_date.present? %>
                    <span class="float-start">
                      <small class="text-secondary">
                        Aggiornato da:
                        &nbsp;
                        <%= @hourly_permit.updater %>
                        &emsp;
                        Data Ultimo Aggiornamento:
                        &nbsp;
                        <%= l(@hourly_permit.update_date, format: "%A %d %B %Y") %>
                      </small>
                    </span>
                  <% end %>
                  <br/>
                  <span class="float-end">
                    <small class="text-success">
                      <% if processed_hourly_permit(hourly_permit) %>
                        <i class="fa-solid fa-circle-check"></i>
                        &nbsp;
                        Presa Visione
                      <% end %>
                    </small>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/hourly_permits/_form.html.erb
<%= form_with(model: hourly_permit) do |form| %>
  <% if hourly_permit.errors.any? %>
    <div style="color: red">
      <h4>
        Errore!&emsp;Non posso salvare per i seguenti motivi:
      </h4>
      <ul>
        <% hourly_permit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% unless current_user.regular == true %>
    <div class="input-group mb-1">
      <span class="input-group-text">
        <i class="fa-solid fa-user"></i>
        &nbsp;&nbsp;
        <%= form.label :user %>
      </span>
      <% unless current_user.god == true %>
        <%= form.collection_select :user_id, User.order('last_name ASC').where(province: current_user.province, region: current_user.region), :id, :user_name_full, {:include_blank => false}, {:class => 'form-control'} %>
      <% else %>
        <%= form.collection_select :user_id, User.order('last_name ASC'), :id, :user_name_full, {:include_blank => false}, {:class => 'form-control'} %>
      <% end %>
    </div>
  <% end %>
  <div class="input-group mb-1">
    <span class="input-group-text">
      <i class="fa-solid fa-calendar-day"></i>
      &nbsp;&nbsp;
      <%= form.label :permit_type %>
    </span>
    <%= form.collection_select :permit_type_id, PermitType.order("position ASC"), :id, :name, { :include_blank => false }, { :class => "form-control" } %>
  </div>
  <div class="input-group mb-1">
    <span class="input-group-text">
      <i class="fa-solid fa-calendar-day"></i>
      &nbsp;&nbsp;
      <%= form.label :start_date %>
    </span>
    <%= form.datetime_field :start_time, class: 'form-control' %>
  </div>
  <div class="input-group mb-1">
    <span class="input-group-text">
      <i class="fa-solid fa-calendar-day"></i>
      &nbsp;&nbsp;
      <%= form.label :end_date %>
    </span>
    <%= form.datetime_field :end_time, class: 'form-control' %>
  </div>
  <div class="input-group mb-2">
    <span class="input-group-text">
      <i class="fa-solid fa-pencil"></i>
      &nbsp;&nbsp;
      <%= form.label :note %>
    </span>
    <%= form.text_area :note, class: 'form-control' %>
  </div>
  <% unless current_user.regular == true %>
    <br/>
    <div class="form-check form-check-inline">
      <label class="form-check-label text-primary" for="checkboxPrefilled">
        Presa visione
        &nbsp;&nbsp;
        <i class="fa-solid fa-eye"></i>
      </label>
      <%= form.check_box :processed, class: 'form-check-input' %>
    </div>
    <br/>
    <br/>
  <% end %>
  <div class="d-grid">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/hourly_permits/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header mb-5">
          <div class="modal-title">
            <%= image_tag("hourly_permits_form_icon.svg", class: "img-fluid") %>
          </div>
          <a class="modal-header-link" data-bs-dismiss="modal" aria-label="Close">
            <i class="fa-solid fa-xmark"></i>
          </a>
        </div>
        <div class="modal-body mb-5">
          <div class="col-8 offset-2">
            <%= render "hourly_permits/form", hourly_permit: hourly_permit %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/hourly_permits/_hourly_holiday.html.erb
<div id="<%= dom_id hourly_permit %>" class="scaffold_record">
  <p>
    <strong>Name:</strong>
    <%= hourly_permit.id %>
  </p>
  <strong>Position:</strong>
  <%= hourly_permit.start_time %>
</p>
</div>

app/views/hourly_permits/edit.html.erb
<h1>Editing hourly_permit</h1>
<%= render "form", hourly_permit: @hourly_permit %>
<br>
<div>
  <%= link_to "Show this hourly_permit", @hourly_permit %> |
  <%= link_to "Back to hourly_permits", hourly_permits_path %>
</div>

app/views/hourly_permits/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "hourly_permits/form_modal", locals: { hourly_permit: @hourly_permit } %>
<% end %>

app/views/hourly_permits/index.html.erb
<div class="row">
  <div class="col-8">
    <h3 class='text-primary'>
      <%= image_tag("hourly_permits_logo.svg", class: "img-fluid") %>
    </h3>
  </div>
  <div class="col-4">
    <div class="d-grid">
      <%= link_to new_hourly_permit_path, "data-controller": "turbo", class: "btn btn-primary btn-sm shadow" do %>
        <i class="fa-solid fa-plus"></i>
        &nbsp;
        <i class="fa-regular fa-clock"></i>
        &nbsp;
        <i class="fa-solid fa-graduation-cap"></i>
        &nbsp;
        Aggiungi Ore Permesso
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12">
    <%= month_calendar(events: @hourly_permits) do |date, hourly_permits| %>
      <% if date.wday == 0 || date.wday == 6 %>
      <% else %>
        <div class='card card-calendar bg-light mb-1 shadow'>
          <div class='card-header card-header-calendar text-center'>
            <i class='fas fa-calendar-day'></i>
            &nbsp;
            <%= l(date, format: "%a %d") %>
            &emsp;
            <span class='text-secondary'>
              <%= l(date, format: "%b") %>
            </span>
          </div>
          <div class='card-body card-body-calendar'>
            <% hourly_permits.each do |hourly_permit| %>
                <% if hourly_permit.user.color? %>
                  <span class="badge" style="background-color: <%= "#{hourly_permit.user.color}" %>">
                <% else %>
                  <span class="badge">
                <% end %>
                <%= link_to hourly_permit_path(hourly_permit), "data-controller": "turbo", "data-bs-toggle": "tooltip", "title": "Visualizza Dettaglio" do %>
                  <i class='fas fa-user'></i>
                  &nbsp;
                  <%= "#{hourly_permit.user.last_name} #{hourly_permit.user.first_name.split.map { |i| i[0, 1].upcase }.join}" %>
                <% end %>
                <span class="text-dark">
                  <% if processed_hourly_permit(hourly_permit) %>
                  <% else %>
                    &emsp;
                    |
                    &emsp;
                    <%= link_to edit_hourly_permit_path(hourly_permit), "data-controller": "turbo", "data-bs-toggle": "tooltip", "title": "Modifica il Record Corrente" do %>
                      <i class="fa-solid fa-pen-to-square"></i>
                    <% end %>
                    &nbsp;
                    &nbsp;
                    <%= link_to hourly_permit_path(hourly_permit), "data-turbo-method": :delete, "data-turbo-confirm": "Sicuri di voler eliminare il record corrente?", "data-bs-toggle": "tooltip", "title": "Elimina il Record Corrente" do %>
                      <i class="fa-solid fa-trash"></i>
                    <% end %>
                  <% end %>
                </span>
              </span>
              <br/>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/hourly_permits/new.html.erb
<h1>New Hourlypermit</h1>
<%= render "form", hourly_permit: @hourly_permit %>
<br>
<div>
  <%= link_to "Back to hourly_permits", hourly_permits_path %>
</div>

app/views/hourly_permits/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "hourly_permits/form_modal", locals: { hourly_permit: @hourly_permit } %>
<% end %>

app/views/hourly_permits/search.html.erb
<div class="row mb-4">
  <div class="col-12">
    <%= image_tag("hourly_permits_logo.svg", class: "img-fluid") %>
  </div>
</div>
<%= search_form_for @q, id: "search-form", url: search_hourly_permits_path do |form| %>
  <div class="row">
    <div class="col-4">
      <div class="input-group mb-2">
        <div class="input-group-search">
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;<span>Data Inizio</span>
        </div>
        <%= form.date_field :start_time_gteq, class: "form-control" %>
      </div>
    </div>
    <div class="col-4">
      <div class="input-group mb-2">
        <div class="input-group-search">
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;<span>Data Fine</span>
        </div>
        <%= form.date_field :start_time_lteq, class: "form-control" %>
      </div>
    </div>
    <div class="col-4">
      <span class="float-start">
        <div class="input-group mb-2">
          <div class="input-group-search">
            <i class="fa-solid fa-user-circle"></i>
            &nbsp;<span>Utente</span>
          </div>
          <% if god? %>
            <%= form.collection_select(:user_id_eq, User.order("last_name ASC"), :id, :user_name_full, { :include_blank => true }, { :class => "form-control" }) %>
          <% elsif manager? %>
            <%= form.collection_select :user_id_eq, User.order("last_name ASC").where(province: current_user.province, region: current_user.region), :id, :user_name_full, { :include_blank => true }, { :class => "form-control" } %>
          <% else %>
          <% end %>
        </div>
      </span>
      <span class="float-end pe-2">
        <%= button_tag(type: "submit", class: "btn btn-primary") do %>
          <i class="fa-solid fa-magnifying-glass"></i>
          &emsp;
          <strong>
            Cerca
          </strong>
        <% end %>
        &nbsp;
      </span>
    </div>
  </div>
<% end %>
<div class="row">
  <div class="col-12">
    <br/>
    <table class="table table-hover text-primary">
      <thead>
        <th>
          <i class="fa-solid fa-user-circle"></i>
          &nbsp;
          Utente
        </th>
        <th>
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;
          Data Ora Inizio
        </th>
        <th>
          <i class="fa-solid fa-calendar-day"></i>
          &nbsp;
          Data Ora Fine
        </th>
        <th>
          <i class="fa-solid fa-calendar-days"></i>
          &nbsp;
          Durata
        </th>
      </thead>
      <tbody>
        <% @total = 0 %>
        <% @hourly_permits.each do |hourly_permit| %>
          <% if hourly_permit.user.color? %>
            <tr style="background-color: <%= "#{hourly_permit.user.color}" %>">
            <% else %>
              <tr>
              <% end %>
              <td>
                <%= link_to hourly_permit_path(hourly_permit), "data-controller": "turbo", "data-bs-toggle": "tooltip", "title": "Visualizza Dettaglio" do %>
                  <%= "#{hourly_permit.user.first_name} #{hourly_permit.user.last_name}" %>
                <% end %>
              </td>
              <td>
                <%= l(hourly_permit.start_time, format: "%A %d %B %Y dalle ore: %H:%M") %>
              </td>
              <td>
                <%= l(hourly_permit.end_time, format: "%A %d %B %Y alle ore: %H:%M") %>
              </td>
              <td>
                <strong class='text-primary'>
                  <%= hourly_permit_duration(hourly_permit).round %>
                  &emsp;
                  <% unless hourly_permit_duration(hourly_permit) > 1 %>
                    ore
                  <% else %>
                    ore
                  <% end %>
                </strong>
              </td>
            </tr>
            <% @total = @total + hourly_permit_duration(hourly_permit).round %>
          <% end %>
        </tbody>
      </table>
      <br>
      <%= paginate @hourly_permits %>
    </div>
  </div>

app/views/hourly_permits/show.html.erb
<%= render @hourly_permit %>
<div>
  <%= link_to "Edit", edit_hourly_permit_path(@hourly_permit) %> |
  <%= link_to "Destroy", hourly_permit_path(@hourly_permit),
    "data-turbo-method": :delete,
    "data-turbo-confirm": "Are you sure?" %> |
  <%= link_to "Back to hourly_permits", hourly_permits_path %>
</div>

app/views/hourly_permits/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "hourly_permits/detail", locals: { hourly_permit: @hourly_permit } %>
<% end %>