config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get "home/index"
  get "home/credits"
  get "dashboard/index"
  get "dashboard/search"
  get "dashboard/whatsup"
  get "dashboard/peruser"

  resources :roads
  resources :transports
  resources :places
  resources :structures
  resources :reasons
  resources :veichles
  resources :refunds do
    collection do
      get :print
      get :print_list
    end
  end
  resources :refund_closures do
    collection do
      get :search
    end
  end
  resources :holidays do
    collection do
      get :search
    end
  end
  resources :hourly_holidays do
    collection do
      get :search
    end
  end
  resources :diseases do
    collection do
      get :search
    end
  end
  resources :permits do
    collection do
      get :search
    end
  end
  resources :hourly_permits do
    collection do
      get :search
    end
  end

  devise_for :users, skip: [:registrations]
  as :user do
    get "users/edit" => "devise/registrations#edit", :as => "edit_user_registration"
    put "users" => "devise/registrations#update", :as => "user_registration"
    resources :users, only: [:index, :show]
  end

  mount RailsAdmin::Engine => "/admin", as: "rails_admin"
end

app/models/refund.rb
class Refund < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :place, optional: true
  belongs_to :reason, optional: true
  belongs_to :veichle, optional: true
  belongs_to :road, optional: true
  belongs_to :structure, optional: true
  belongs_to :transport, optional: true

  before_create :set_refund_number

  def set_refund_number
    last_refund_number = Refund.maximum(:refund_number)
    self.refund_number = last_refund_number.to_i + 1
  end

  before_save :fill_free_fields, :calculate_total

  # It fill free fields(_fr) from associations
  def fill_free_fields
    if self.user_id != nil
      self.user_fr = "#{self.user.first_name} #{self.user.last_name}"
    end

    if self.reason_id != nil
      self.reason_fr = self.reason.name
    end

    if self.road_id != nil
      self.road_fr = self.road.name
      if self.road.highway_cost != nil
        self.highway_cost_fr = self.road.highway_cost
      end
      if self.road.road_lenght != nil
        self.road_lenght_fr = self.road.road_lenght
      end
    end

    if self.place_id != nil
      self.place_fr = self.place.name
    end

    if self.structure_id != nil
      self.structure_fr = self.structure.name
    end

    if self.transport_id != nil
      self.transport_fr = self.transport.name
    end

    if self.veichle_id != nil
      self.veichle_fr = "#{self.veichle.producer} #{self.veichle.name} con targa: #{self.veichle.license_plate}"
    end
  end

  # It sum the expences fields to create total_amount
  def calculate_total
    if self.food_cost != nil
      food = self.food_cost
    else
      food = 0.00
    end

    if self.parking_cost != nil
      parking = self.parking_cost
    else
      parking = 0.00
    end

    if self.room_cost != nil
      room = self.room_cost
    else
      room = 0.00
    end

    if self.ticket_cost != nil
      ticket = self.ticket_cost
    else
      ticket = 0.00
    end

    if self.generic_cost != nil
      generic = self.generic_cost
    else
      generic = 0.00
    end

    if self.road_id != nil && self.road.highway_cost != nil
      highway = self.road.highway_cost
      self.highway_cost_fr = self.road.highway_cost
    elsif self.highway_cost_fr != nil
      highway = self.highway_cost_fr
    else
      highway = 0.00
    end

    # Check if it is a veichle and what type of
    if self.transport.name == "Veicolo Aziendale" # company veichle
      sum_value = food + parking + room + ticket + generic + highway
    elsif self.transport.name == "Veicolo Privato" # private veichle
      if self.road_id != nil
        partial_cost = self.road.road_lenght * self.user.cost_per_km
      else
        partial_cost = self.road_lenght_fr * self.user.cost_per_km
      end
      sum_value = food + parking + room + ticket + generic + highway + partial_cost
    else
      sum_value = food + parking + room + ticket + generic
    end

    self.total_amount = sum_value
  end

  # Validations
  validates :departure_date, :return_date, :request_date, :refund_date, :transport_id, presence: true
end

app/controllers/refunds_controller.rb
class RefundsController < ApplicationController
  load_and_authorize_resource

  before_action :set_refund, only: %i[ show edit update destroy ]

  before_action do
    ActiveStorage::Current.host = request.base_url
  end

  def index
    @refunds = Refund.where(user_id: current_user.id).order(created_at: "DESC").page(params[:page])
  end

  def show
    @refund = Refund.find(params[:id])
  end

  def print
    @q = Refund.ransack(params[:q])
    @refunds = @q.result(distinct: true).order(refund_number: "DESC").where(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: "refunds/print", pdf: "print" }
    end
  end

  def print_list
    @q = Refund.ransack(params[:q])
    @refunds = @q.result(distinct: true).order(refund_number: "DESC").where(user_id: current_user.id)
    respond_to do |format|
      format.html
      format.json
      format.pdf { render template: "refunds/print_list", pdf: "print_list" }
    end
  end

  def new
    @refund = Refund.new
  end

  def edit
  end

  def create
    @refund = current_user.refunds.build(refund_params)

    if @refund.save
      redirect_to refunds_path, notice: "refund was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @refund.update(refund_params)
      redirect_to refunds_path, notice: "refund was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @refund.destroy
    redirect_to refunds_url, notice: "refund was successfully destroyed."
  end

  private

  def set_refund
    @refund = Refund.find(params[:id])
  end

  def refund_params
    params.require(:refund).permit(:refund_number, :departure_date, :return_date, :request_date, :refund_date, :parking_cost, :food_cost, :room_cost, :ticket_cost, :generic_cost, :total_amount, :user_id, :place_id, :reason_id, :veichle_id, :road_id, :structure_id, :transport_id, :place_fr, :reason_fr, :road_fr, :structure_fr, :transport_fr, :veichle_fr, :road_lenght_fr, :highway_cost_fr)
  end
end

app/helpers/refunds_helper.rb
module RefundsHelper
  def used_veichle(refund)
    if refund.veichle_id != nil
      ("Ho usato il seguente veicolo: <strong>#{refund.veichle_fr}</strong>.").html_safe
    end
  end

  def departure_gender(refund)
    if refund.user.sex == "M"
      "Sono partito il giorno "
    elsif refund.user.sex == "F"
      "Sono partita il giorno "
    else
      "Sono partit* il giorno "
    end
  end

  def return_gender(refund)
    if refund.user.sex == "M"
      "Sono rientrato in sede il giorno "
    elsif refund.user.sex == "F"
      "Sono rientrata il giorno "
    else
      "Sono rientrat* il giorno "
    end
  end

  def incurred_prking_cost(refund)
    if refund.parking_cost != nil && refund.parking_cost > 0.00
      ("<li>Parcheggio: #{number_to_currency(refund.parking_cost)}</li>").html_safe
    end
  end

  def incurred_food_cost(refund)
    if refund.food_cost != nil && refund.food_cost > 0.00
      ("<li>Vitto: #{number_to_currency(refund.food_cost)}</li>").html_safe
    end
  end

  def incurred_room_cost(refund)
    if refund.room_cost != nil && refund.room_cost > 0.00
      ("<li>Alloggio: #{number_to_currency(refund.room_cost)}</li>").html_safe
    end
  end

  def incurred_ticket_cost(refund)
    if refund.ticket_cost != nil && refund.ticket_cost > 0.00
      ("<li>Ticket: #{number_to_currency(refund.ticket_cost)}</li>").html_safe
    end
  end

  def incurred_generic_cost(refund)
    if refund.generic_cost != nil && refund.generic_cost > 0.00
      ("<li>Varie: #{number_to_currency(refund.generic_cost)}</li>").html_safe
    end
  end

  def incurred_highway_cost(refund)
    if refund.highway_cost_fr != nil && refund.highway_cost_fr > 0.00
      ("<li>Costo Autostrada: #{number_to_currency(refund.highway_cost_fr)}</li>").html_safe
    end
  end

  def incurred_private_veichle_cost(refund)
    if refund.transport.name == "Veicolo Privato"
      ("<li> Costo Totale Percorso: #{number_to_currency(refund.user.cost_per_km * refund.road_lenght_fr)}</li>").html_safe
    end
  end

  def conditional_syle_prefilled_forms(refund)
    if refund.reason_id != nil ||
       refund.road_id != nil ||
       refund.place_id != nil ||
       refund.structure_id != nil
      "display:block"
    else
      "display:none"
    end
  end

  def conditional_syle_free_forms(refund)
    if refund.reason_id != nil ||
       refund.road_id != nil ||
       refund.place_id != nil ||
       refund.structure_id != nil
      "display:none"
    elsif refund.reason_fr != nil ||
          refund.road_fr != nil ||
          refund.place_fr != nil ||
          refund.structure_fr != nil
      "display:block"
    else
      "display:none"
    end
  end
end

app/views/refunds/_detail.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header mb-5">
          <div class="modal-title">
            <%= image_tag("refunds_form_icon.svg", class: "img-fluid") %>
          </div>
          <a class="modal-header-link" data-bs-dismiss="modal" aria-label="Close">
            <i class="fa-solid fa-xmark"></i>
          </a>
        </div>
        <div class="modal-body mb-5">
          <div class="col-8 offset-2">
            <div id="<%= dom_id @refund %>" class="scaffold_record">
              <div class="row">
                <div class="col">
                  <h4 class="text-primary">
                    Missione numero: <strong><%= @refund.refund_number %></strong>
                  </h4>
                  <hr class="bg-primary"/>
                  Ho inoltrato la Richiesta Missione il giorno: <strong><%= l(@refund.request_date) %></strong>.
                  <br/>
                  <%= departure_gender(@refund) %> <strong><%= l(@refund.departure_date) %></strong> verso <strong><%= @refund.place_fr %></strong> per il seguente motivo: <strong><%= @refund.reason_fr %></strong>.
                  <br/>
                  Ho utilizzato i seguenti mezzi di trasporto: <strong>
                    <%= @refund.transport_fr %>
                  </strong>
                  <br/>
                  <%= used_veichle(@refund) %>
                  <br/>
                  Ho sostenuto le seguenti spese:
                  <br/>
                  <ul>
                    <%= incurred_prking_cost(@refund) %>
                    <%= incurred_food_cost(@refund) %>
                    <%= incurred_room_cost(@refund) %>
                    <%= incurred_ticket_cost(@refund) %>
                    <%= incurred_generic_cost(@refund) %>
                    <%= incurred_highway_cost(@refund) %>
                    <%= incurred_private_veichle_cost(@refund) %>
                  </ul>
                  Totale Generale: <strong class="text-primary"><%= number_to_currency(@refund.total_amount) %></strong>
                  <hr class="bg-primary"/>
                  <%= return_gender(@refund) %> <strong><%= l(@refund.return_date) %></strong> ed ho fatto richiesta di rimborso spese il giorno <strong><%= l(@refund.request_date) %></strong>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/refunds/_form_modal.html.erb
<%= turbo_frame_tag :remote_modal, target: :_top do %>
  <div class="modal fade" data-controller="modal">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header mb-2">
          <div class="modal-title">
            <%= image_tag("refunds_form_icon.svg", class: "img-fluid") %>
          </div>
          <a class="modal-header-link" data-bs-dismiss="modal" aria-label="Close">
            <i class="fa-solid fa-xmark"></i>
          </a>
        </div>
        <div class="modal-body mb-1">
          <div class="col">
            <%= render "refunds/form", refund: refund %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/refunds/_refund.html.erb
<div id="<%= dom_id refund %>" class="scaffold_record">
  <p>
    <strong>Refund Number:</strong>
    <%= refund.refund_number %>
  </p>
</div>

app/views/refunds/edit.html.erb
<h1>Editing refund</h1>
<%= render "form", refund: @refund %>
<br>
<div>
  <%= link_to "Show this refund", @refund %> |
  <%= link_to "Back to refunds", refunds_path %>
</div>

app/views/refunds/edit.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "refunds/form_modal", locals: { refund: @refund } %>
<% end %>

app/views/refunds/index.html.erb
<div class="col-3">
  <div class="d-grid mx-3">
    <%= image_tag("refunds_logo.svg", class: "img-fluid") %>
    <%= link_to new_refund_path, "data-controller": "turbo", class: "btn btn-primary btn-sm shadow mb-3" do %>
      <i class="fa-solid fa-plus"></i>
      &nbsp;
      <i class="fa-solid fa-wallet"></i>
      &nbsp;
      Nuovo Rimborso
    <% end %>
  </div>
</div>
<div class="col-9">
  <table class="table table-hover table-striped">
    <thead class="text-primary">
      <th></th>
      <th>
        <i class="fa-solid fa-calendar-day"></i>
        &nbsp;Data Partenza
      </th>
      <th>
        <i class="fa-solid fa-location-dot"></i>
        &nbsp;Luogo
      </th>
      <th>
        <i class="fa-solid fa-building"></i>
        &nbsp;Struttura
      </th>
      <th colspan=2></th>
    </thead>
    <tbody>
      <% @refunds.each do |refund| %>
        <tr>
          <td>
            <%= link_to refund_path(refund), 
            "data-controller": "turbo", 
            class: "btn btn-outline-primary btn-sm",
            "data-bs-toggle": "tooltip", 
            "title": "Visualizza Dettagli" do %>
              <%= refund.refund_number %>
            <% end %>
          </td>
          <td>
            <%= l(refund.departure_date) %>
          </td>
          <td>
            <%= refund.place_fr %>
          </td>
          <td>
            <%= refund.structure_fr %>
          </td>
          <td>
            <%= link_to edit_refund_path(refund), 
            "data-controller": "turbo", 
            "data-bs-toggle": "tooltip", 
            "title": "Modifica il Record Corrente", class: "edit-link" do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
          </td>
          <td>
            <%= link_to refund_path(refund),
            "data-turbo-method": :delete,
            "data-turbo-confirm": "Sicuri di voler eliminare il record corrente?", 
            "data-bs-toggle": "tooltip", 
            "title": "Elimina il Record Corrente", class: "delete-link" do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= paginate @refunds %>
</div>

app/views/refunds/new.html.erb
<h1>New refund</h1>
<%= render "form", refund: @refund %>
<br>
<div>
  <%= link_to "Back to refunds", refunds_path %>
</div>

app/views/refunds/new.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "refunds/form_modal", locals: { refund: @refund } %>
<% end %>

app/views/refunds/print.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= search_form_for @q, id: "search-form", url: print_refunds_path do |form| %>
        <%= image_tag("refunds_print_logo.svg", class: "img-fluid mb-5") %>
        <div class="row">
          <div class="col-4">
            <div class="input-group mb-2">
              <div class="input-group-text">
                <i class="fa-solid fa-calendar-day"></i>
                &nbsp;<span>Data Inizio</span>
              </div>
              <%= form.date_field :departure_date_gteq, class: "form-control" %>
            </div>
          </div>
          <div class="col-4">
            <div class="input-group mb-2">
              <div class="input-group-text">
                <i class="fa-solid fa-calendar-day"></i>
                &nbsp;<span>Data Fine</span>
              </div>
              <%= form.date_field :departure_date_lteq, class: "form-control" %>
            </div>
          </div>
          <div class="col-4">
            <span class="float-end">
              <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                <i class="fa-solid fa-magnifying-glass"></i>
                &emsp;
                <strong>
                  Cerca
                </strong>
              <% end %>
              &nbsp;
              <%= link_to print_refunds_path(request.parameters.merge(format: "pdf")), class: "btn btn-primary", target: :_blank do %>
                <i class="fa-solid fa-print"></i>
                &emsp;
                Stampa
              <% end %>
            </span>
          </div>
        </div>
        <br/>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12">
      <table class="table table-striped">
        <thead class="text-primary">
          <th></th>
          <th>
            <i class="fa-solid fa-calendar-day"></i>
            &nbsp;Data Partenza
          </th>
          <th>
            <i class="fa-solid fa-location-dot"></i>
            &nbsp;Luogo
          </th>
          <th>
            <i class="fa-solid fa-building"></i>
            &nbsp;Struttura
          </th>
          <th colspan=2></th>
        </thead>
        <tbody>
          <% @refunds.each do |refund| %>
            <tr>
              <td>
                <%= refund.refund_number %>
              </td>
              <td>
                <%= l(refund.departure_date) %>
              </td>
              <td>
                <%= refund.place_fr %>
              </td>
              <td>
                <%= refund.structure_fr %>
              </td>
              <td>
              </td>
              <td>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/refunds/print_list.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <%= search_form_for @q, id: "search-form", url: print_list_refunds_path do |form| %>
        <%= image_tag("refunds_print_list_logo.svg", class: "img-fluid mb-5") %>
        <div class="row">
          <div class="col-4">
            <div class="input-group mb-2">
              <div class="input-group-text">
                <i class="fa-solid fa-calendar-day"></i>
                &nbsp;<span>Data Inizio</span>
              </div>
              <%= form.date_field :departure_date_gteq, class: "form-control" %>
            </div>
          </div>
          <div class="col-4">
            <div class="input-group mb-2">
              <div class="input-group-text">
                <i class="fa-solid fa-calendar-day"></i>
                &nbsp;<span>Data Fine</span>
              </div>
              <%= form.date_field :departure_date_lteq, class: "form-control" %>
            </div>
          </div>
          <div class="col-4">
            <span class="float-end">
              <%= button_tag(type: "submit", class: "btn btn-primary") do %>
                <i class="fa-solid fa-magnifying-glass"></i>
                &emsp;
                <strong>
                  Cerca
                </strong>
              <% end %>
              &nbsp;
              <%= link_to print_list_refunds_path(request.parameters.merge(format: "pdf")), class: "btn btn-primary", target: :_blank do %>
                <i class="fa-solid fa-print"></i>
                &emsp;
                Stampa Riepilogo
              <% end %>
            </span>
          </div>
        </div>
        <br/>
      <% end %>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-12">
      <table class="table table-striped">
        <thead class="text-primary">
          <th></th>
          <th>
            <i class="fa-solid fa-calendar-day"></i>
            &nbsp;Data Partenza
          </th>
          <th>
            <i class="fa-solid fa-location-dot"></i>
            &nbsp;Luogo
          </th>
          <th>
            <i class="fa-solid fa-building"></i>
            &nbsp;Struttura
          </th>
          <th colspan=2></th>
        </thead>
        <tbody>
          <% @refunds.each do |refund| %>
            <tr>
              <td>
                <%= refund.refund_number %>
              </td>
              <td>
                <%= l(refund.departure_date) %>
              </td>
              <td>
                <%= refund.place_fr %>
              </td>
              <td>
                <%= refund.structure_fr %>
              </td>
              <td>
              </td>
              <td>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/refunds/print_list.pdf.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8'/>
    <%= stylesheet_link_tag wicked_pdf_asset_base64('print_list.scss') %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col">
          <span class="span-right">
            <%= inline_svg('pdf/refunds_logo_riepilogo.svg', preserve_aspect_ratio: 'xMaxYMax meet') %>
          </span>
          <br/>
          <br/>
          <br/>
          <%= inline_svg('pdf/cgil_logo.svg', preserve_aspect_ratio: 'xMaxYMax meet') %>
          <hr/>
          <br/>
          <table align="center">
            <thead>
              <tr>
                <th class="td-institute"><strong>Utente</strong></th>
                <th class="td-institute"><strong>Istituto</strong></th>
                <th class="td-date"><strong>Data</strong></th>
                <th class="td-date"><strong>Luogo</strong></th>
                <th class="td-date"><strong>Ammontare</strong></th>
              </tr>
            </thead>
            <tbody>
              <% @total = 0 %>
              <% @refunds.each do |refund| %>
                <tr>
                  <td class="td-institute"><%= "#{refund.user.first_name} #{refund.user.last_name}" %></td>
                  <td class="td-institute"><%= refund.user.institute %></td>
                  <td class="td-date"><%= l(refund.departure_date) %></td>
                  <td><%= refund.place_fr %></td>
                  <td class="td-date"><%= number_to_currency(refund.total_amount) %></td>
                </tr>
                <% @total = @total + refund.total_amount %>
              <% end %>
            </tbody>
          </table>
          <br/>
          <hr/>
          <br/>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <span class="span-right">
            <h3>
              Totale:
              &emsp;
              <strong>
                <%= number_to_currency(@total) %>
              </strong>
              &emsp;
            </h3>
          </span>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/refunds/show.html.erb
<%= render @refund %>
<div>
  <%= link_to "Edit", edit_refund_path(@refund) %> |
  <%= link_to "Destroy", refund_path(@refund),
    "data-turbo-method": :delete,
    "data-turbo-confirm": "Are you sure?" %> |
  <%= link_to "Back to refunds", refunds_path %>
</div>

app/views/refunds/show.turbo_stream.erb
<%= turbo_stream.replace "remote_modal" do %>
  <%= render partial: "refunds/detail", locals: { refund: @refund } %>
<% end %>